jwt:
  secret: should-not-be-exposed-here
  expiration: 36000000

server:
  port: ${PORT:0}
spring:
  application:
    name: users
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}